using System;
//boilerplate auto generated by C# compiler 9.0
Console.WriteLine("Hello World!");
Console.Write("Enter your name: "); 
string name = Console.ReadLine();
Console.WriteLine("Hello {0}!!", name);     
